apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-react
  template:
    metadata:
      labels:
        app: post-react
    spec:
      containers:
      - name: post-react
        image: gcr.io/level-slate-373806/dev-echo-connect-post-react
        ports:
        - containerPort: 8080

        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: secret-envs
              key: MONGO_URI
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: secret-envs
              key: ENCRYPTION_KEY
        - name: GOOGLE_APPLICATION_CREDENTIALS_CONTENT
          valueFrom:
            secretKeyRef:
              name: secret-envs
              key: GOOGLE_APPLICATION_CREDENTIALS_CONTENT

---
apiVersion: v1
kind: Service
metadata:
  name: post-react
spec:
  type: NodePort
  selector:
    app: post-react
  ports:
  - port: 8080
    targetPort: 8080
